language: c

sudo: true

compiler:
- clang
- gcc

addons:
  apt:
    packages:
    - uuid-dev
    - uuid-runtime

install:
- sudo apt-get install clang-format

script:
- make
- clang-format -i sml/include/sml/* sml/src/*
- test -z "$(git status --porcelain)" || (git status; git diff; false)
