language: c

sudo: false

addons:
  apt:
    sources:
    - llvm-toolchain-trusty
    packages:
    - clang-format-9
    - uuid-dev
    - uuid-runtime

before_script:
- clang-format --version

matrix:
  include:
  - compiler: clang
    env: MAKE=1
  - compiler: gcc
    env: MAKE=1
  - env: FORMAT=1

script:
- |
  if [ "$FORMAT" = 1 ]; then
    clang-format -i sml/include/sml/* sml/src/*
    test -z "$(git status --porcelain)" || (git status; git diff; false)
  fi
- if [ "$MAKE" = 1 ]; then make; fi
