language: c

sudo: true

addons:
  apt:
    packages:
    - uuid-dev
    - uuid-runtime

install:
- sudo apt-get install clang-format
- clang-format --version

matrix:
  include:
  - compiler: clang
  - compiler: gcc
  - env: RUN=format

script:
- |
  if [ "$RUN" = "format" ]; then
    clang-format -i sml/include/sml/* sml/src/*
    test -z "$(git status --porcelain)" || (git status; git diff; false)
  fi
- if [ "$RUN" != "format" ]; then make; fi
