language: c

sudo: false

addons:
  apt:
    packages:
    - clang-format-9
    - uuid-dev
    - uuid-runtime

before_script:
- clang-format --version

matrix:
  include:
  - compiler: clang
  - compiler: gcc
  - env: RUN=format

script:
- |
  if [ "$RUN" = "format" ]; then
    clang-format -i sml/include/sml/* sml/src/*
    test -z "$(git status --porcelain)" || (git status; git diff; false)
  fi
- if [ "$RUN" != "format" ]; then make; fi
