language: c

sudo: false

addons:
  apt:
    sources:
    - llvm-toolchain-trusty
    packages:
    - clang-format-9
    - uuid-dev
    - uuid-runtime

before_script:
- clang-format --version

matrix:
  include:
  - env: BUILD=1
    compiler: clang
  - env: BUILD=1
    compiler: gcc
  - env: FORMAT=1

script:
- if [ -n "$BUILD" ]; then make; fi
- |
  if [ -n "$FORMAT" ]; then
    clang-format -i sml/include/sml/* sml/src/*
    test -z "$(git status --porcelain)" || (git status; git diff; false)
  fi
